on: [push, pull_request]
name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.13.x, 1.14.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Lint Code Base
      uses: github/super-linter@v2.0.0
      env:
        # VALIDATE_ALL_CODEBASE: false
        VALIDATE_ANSIBLE: false
    - name: Test
      run: go test ./...